15 display all attachment types
uchicago-library/attachment-converter pull request #28
Opened 2022-03-30 22:58 UTC by nmmull

Fairly straightforward. Just a few notes:
* I added *very* simple flag handling in the executable. As we add more flags, we will definitely want to use one of the packages that Matt has mentioned.
* I tested on a couple of the `mbox`s we have access to, seems to work alright, a bit slow, but I don't think it could be terribly faster unless it was parallelized.

2022-04-01 15:16 UTC, bufordrat requested changes
This is awesome.  One small thing: I got this output on one of my tests:

```console
$ dune exec -- ./main.exe --report < path/to/matts/example/Sent.mbox
Attachment Types:    
        text/plain
  application/msword
  application/octet-stream
  application/pdf
  application/rtf
  application/vnd.ms-excel
  application/vnd.ms-powerpoint
  image/gif
  image/jpeg
  text/html
  text/plain

```
Not sure off the top of my head what causes the extra indented `text/plain` at the beginning, but if an easy fix suggests itself, might be worth doing.  Does whitespace need to get trimmed off the MIME type strings?  Not sure.  I can provide the MBOX that does this if you can't replicate it.

One other example:

```console
$ dune exec -- ./main.exe --report < path/to/matts/example/In-7-02.mbox
Attachment Types:    
  Text/Plain
  application/octet-stream
  application/rtf
  text/plain
  text/x-vcard
```
The double `text/plain` situation suggests it might be a good idea to downcase all the MIME strings before deduping them.

2022-04-01 15:24 UTC, waclena commented
Matt Teichman ***@***.***> writes:

> Not sure off the top of my head what causes the extra indented
> text/plain at the beginning, but if an easy fix suggests itself, might
> be worth doing. Does whitespace need to get trimmed off the MIME type
> strings? Not sure.

Mime headers in parts are exactly like normal mail headers at the top of
a message.  In the latter case, there can be any amount of whitespace
separating the header name from the value, so the same is true for
headers in mime parts.  So the value part of these two headers:

    Content-Type: text/plain
    Content-Type:                  text/plain

should be the same: "text/plain".

I'd expect the ocamlnet header parser to return it correctly, but if it
doesn't I think we should String.(trim whitespace) the value.

2022-04-03 22:34 UTC, nmmull commented on main.ml
> +(* A _very_ minimial executable *)
Noted, fixed. Thanks for pointing it out.

2022-04-03 22:37 UTC, nmmull commented
Yeah, admittedly what I'm doing is super basic, I wanted to see if we could get away without using the ocamlnet parser.

But I think the issue was just a dumb one, I was trimming spaces instead of all whitespace. Fixed this, I probably won't be able to test it until Wednesday but since it was such a simple fix, I pushed it and you can review/test it before then if you have time.

2022-04-04 21:20 UTC, merged