26 Preliminary Testing Part 1
uchicago-library/attachment-converter pull request #36
Opened 2022-06-01 15:35 UTC by nmmull

We are now converting emails (somewhat) successfully. I've added 5 test emails, that cover the conversions that we set out to work with at the outset of the project (at least when I joined). There is an issue with nested emails that needs to be dealt with but I think this is a reasonable point to close this issue and move to a new round of testing.

The main note is that I changed the way tests are dealt with. You have to symbolically link the `test_emails` directory I created in the shared email data source to a directory `test/test_emails` in the project. This avoids the need to create a separate private repository.

This branch subsumes `nathan-second-round-testing`, so that pull request can be ignored. I'm creating this one so that it closes the testing issue.

2022-06-03 21:20 UTC, bufordrat requested changes
Man, this is really coming along.  Amazing work!  Lot to look at here; I'll note that I tried it on a bunch of random emails I had lying around and they all seemed to be working great.  I also tried messing with the extension field in the config, for example adding a `.TGA` extension to the pdfs converted from docs, just to see what would happen.  It was as you'd expect.  I left the dot off the extension the first time---just noting that that's something we'll want to remember to cover in the documentation.

We are getting dangerously close to having an alpha version of this thing!  My only suggestion before merging this in is to convert the first try/with example to a `Result.trap`.  Up to you whether you'd like to make the rest of the try-s into exception-catching pattern matches.

2022-06-08 19:25 UTC, nmmull commented on lib/convert.ml
> +    try
Very cool pattern. Made the fix.

2022-06-08 19:25 UTC, nmmull commented on lib/convert.ml
> +      >>| update_filename_string ~tstamped:tstamped ~star:star ext
It's mostly for testing, so that it can be made deterministic.

2022-06-08 19:25 UTC, nmmull commented on lib/convert.ml
> +      let args = split script in
Updated.

2022-06-08 19:26 UTC, nmmull commented on lib/convert.ml
> +        try
Updated.

2022-06-08 19:26 UTC, nmmull commented on lib/report.ml
> +  let module M       = Map.Make(String)                                        in
It's the most natural way I could think of to do counting. Out of curiosity, is there another way you would have approached it?

2022-06-29 20:37 UTC, merged